name: ci

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: nix flake check
        run: nix flake check --print-build-logs
      - name: nix build default bundle
        run: nix build .#default --print-build-logs
